### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by istotaD503** [CBANcapstone/Exquisite-Comics#9]

**Comment by richardbmx** [comment]
Hello my name is Richard I am a graphic designer and I love making contributions for open source projects, I see that you do not have a defined logo for your application. If you want I can do it for you without any problem you just have to authorize me to do it ... regards. ..

**Comment by istotaD503** [comment]
Hi Richard. Thanks for your offer, I highly appreciate it! However, at this time we do not need to design a logo for our project.
